drop database librarydb;
create database librarydb;
use librarydb;


create table books
(
	book_id int auto_increment primary key,
    bk_title varchar(50),
    author varchar(50),
    total_copies int,
    available_copies int
);


create table customers
(
	cust_id int auto_increment primary key,
    cname varchar(50),
    cemail varchar(30),
    phone_no varchar(20)
);

create table borrow_records
(
	borrow_id int auto_increment primary key,
    book_id int,
    cust_id int,
    borrow_date date,
    returned_date date,
    bk_status varchar(20),
    foreign key (cust_id) references customers(cust_id),
    foreign key (book_id) references books(book_id)
);

INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Arm picture', 'Nicholas Rodgers', 9, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Walk war', 'Tracy Simmons', 11, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Stand', 'Pedro Schwartz', 17, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Social consumer attorney', 'Kathleen Campbell', 9, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Modern recently get', 'Richard Sandoval', 25, 25);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Story structure', 'Jennifer Hernandez', 13, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Anyone hear billion', 'Amanda Barnes', 17, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Where purpose', 'John Rose', 20, 14);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('City theory', 'Kayla Kramer', 25, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Use model', 'Kimberly Leon', 24, 15);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Phone political', 'Sharon Lane', 21, 15);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Lawyer anything', 'Nicole Sparks', 19, 14);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Behavior structure', 'Connor Gonzalez', 24, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Under modern', 'Kendra Jones', 19, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Nearly', 'Cory Williams', 10, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Too past', 'Jamie Curtis', 12, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Necessary power', 'Timothy West', 12, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Add practice discussion', 'Melissa Lopez', 17, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Heavy', 'Hunter Wilkinson', 28, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Bill', 'Robert Armstrong', 7, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Drive year structure', 'Benjamin Johnson', 19, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Born fill', 'Juan Johnson', 14, 13);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Part else', 'Sarah Robinson', 9, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Top expert keep', 'Michael Flores', 19, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Enter image he factor', 'Michael Pearson', 25, 24);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('So when ground', 'Sherri Sanders', 18, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Receive similar', 'Lindsey Patterson', 9, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Man population out', 'Samuel Buck', 11, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Agency bank', 'Keith Lewis', 18, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Five federal', 'Luke Novak', 9, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Sometimes responsibility foreign', 'Nicholas Lucero', 12, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Student maintain', 'Jerry Green', 25, 22);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Home common trade', 'Jason Spencer', 10, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('News although since', 'Ryan Cox', 19, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Market sport', 'Ralph Lucas', 24, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Recognize care region', 'Mario Smith', 6, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Practice test them', 'Andrea Petersen', 14, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Thousand summer discover', 'Richard Zamora', 28, 21);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Player garden floor', 'Mike Conley', 7, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Fact lay', 'Lauren Gonzalez', 14, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Natural need sport', 'Mark Rivas PhD', 22, 15);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Full', 'Benjamin Miller', 20, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Glass themselves indeed', 'Ricky Coleman', 20, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Myself future', 'Eric Mcgrath', 23, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Might avoid', 'Scott Thompson', 9, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Voice wide', 'Amanda Fisher', 6, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Arrive animal', 'Dustin Sutton', 5, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Management pick try', 'Sarah Turner', 17, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Difference will', 'Robert George', 14, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Might whose walk', 'Edward Wood', 5, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Teacher job could', 'Shane Walker', 16, 16);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Young so', 'Kendra Evans', 24, 17);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Remember within beyond perhaps', 'Nicole Kemp', 24, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Detail condition take', 'Jamie Wade', 18, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Drop data almost', 'Christina Reeves', 15, 15);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Consumer local', 'Kristin Martinez', 23, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Majority', 'Mr. Steven Price', 22, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Child be', 'Michael Mann', 14, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Kind performance', 'Stanley Bradshaw', 20, 15);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Help it', 'Karen Gonzalez', 25, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Raise least exactly', 'Steven Terry', 26, 26);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Politics', 'Amber Johnson', 26, 15);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Interview stock need', 'Andrew Whitaker', 8, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Degree', 'Benjamin Vaughn', 7, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Develop', 'Richard Campbell', 24, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('High away pretty', 'Karen Garcia', 13, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Foreign knowledge both', 'Whitney Webb', 27, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Trial break', 'Lawrence Lopez', 13, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Message special', 'William Hunter', 15, 13);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Table difference', 'Sabrina Bryant', 21, 13);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Himself while perhaps admit', 'Sherry Daniels', 24, 17);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Return in', 'Matthew Turner DVM', 6, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Account sort', 'Crystal Gutierrez', 23, 22);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Wall', 'Craig Cantrell', 10, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Opportunity federal', 'Douglas Smith', 5, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Add', 'Gene Weaver', 11, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Physical skill strong', 'Mark Frank', 30, 27);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Lot she ground', 'Michael Wood', 27, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Artist very fast', 'Dr. Christina Bryan', 29, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Between pressure law', 'Thomas Drake', 10, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Many benefit fight', 'Lisa Hayes', 7, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Full customer assume tend', 'Christy Ramirez', 18, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Base strategy effort', 'Carlos Velazquez', 14, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Wrong soldier catch', 'Jennifer Ellison', 19, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Far positive side', 'Karen Fowler', 18, 11);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Why especially', 'Lori Vang', 17, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Ahead everything across', 'Jenny King', 9, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Feeling admit', 'Julie Holmes', 21, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Early truth', 'Vanessa James', 7, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Phone street up', 'Brandon Hicks', 30, 16);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Challenge growth interview', 'Ryan Lee', 19, 14);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('At edge yeah', 'Gabrielle Patel', 10, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Develop fly trial drive', 'Glenn Riley', 9, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Tree big time', 'Krystal Long', 8, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Record think drug', 'Eric Lindsey', 28, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Else benefit', 'Joe Williams', 30, 14);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('According bar Mr', 'John Smith', 6, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Song summer behind', 'Randy Doyle', 7, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Message', 'Kimberly Morris', 30, 28);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Pass specific', 'Joseph Robbins', 24, 16);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Bed push stuff', 'John Anderson', 28, 22);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Establish', 'Rebecca Cardenas', 25, 13);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Star risk interest shake', 'Richard Williams', 6, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('By tough in', 'Karen Wilkerson', 26, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Speech do', 'Larry Long', 30, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Find election', 'Lisa Smith', 13, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Certain successful fall', 'Roberto Hughes', 7, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Just behind project', 'Michael Jones', 21, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Care after', 'Amanda Mann', 15, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Future threat candidate brother', 'Amy Mcguire', 14, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Speak near', 'Joseph Cline', 14, 12);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Pressure audience', 'Charlotte Ramirez', 23, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Tend positive everybody', 'Reginald Barber', 17, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Force guess', 'Jacob Peters', 11, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Themselves less', 'Danny Vargas', 29, 11);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Foot nearly', 'Jeffery Walton', 29, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Less protect', 'Laurie Jones', 17, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Describe between', 'Charles Hill', 26, 22);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Body without', 'Kathryn Smith', 17, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Read career', 'Michael Nguyen', 18, 13);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Easy good', 'Ian Pena', 12, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Recently art together', 'Rebecca Anderson', 28, 20);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Fast player', 'Robert Anderson', 21, 16);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Claim fear', 'Scott Graham', 20, 18);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Life attention especially', 'Megan Gonzales', 5, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Happen international although', 'Jeffrey Myers', 10, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Bring analysis although fly', 'Mandy Larson', 7, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Oil board', 'Alexis Patel', 25, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Operation data', 'Kenneth Smith', 10, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Start art animal', 'Taylor White', 5, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Off professor consumer', 'Christopher Smith', 9, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Shake seat', 'Jacqueline Clark', 25, 11);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Bed environment', 'Mark Clark', 17, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Single too', 'Jordan Rodriguez', 13, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Smile reveal', 'Franklin Watkins', 13, 10);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Free term', 'Sarah Jones', 23, 16);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Including assume employee', 'Hailey Henderson', 7, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Ball opportunity responsibility', 'Jennifer Chambers', 29, 19);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Together become', 'Vanessa Espinoza', 10, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('This lot its', 'Stephanie Lynch', 9, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('War attention', 'Veronica Benton', 18, 12);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Again debate different', 'Teresa Johnson DDS', 6, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Forward speech south', 'Erin Leach', 18, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Behind region', 'Michael Wallace', 13, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Almost use author', 'Joseph Ortiz', 19, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Economic floor few', 'Michele Snyder', 7, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Them kid human', 'Angel Porter', 9, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Perhaps not us', 'Rodney Wood', 21, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Gun show build or', 'Mary Gonzales', 14, 14);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Decade eye high ever', 'Brian Wood', 15, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Bank article', 'Jeffrey Cook', 30, 18);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Example key listen travel', 'Catherine Lopez', 15, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Protect watch morning', 'Mark Church', 15, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Page establish officer', 'Emily Anderson', 14, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Sign assume remember', 'Travis Davidson', 27, 18);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Fill', 'Kelly Perkins', 9, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Son season road', 'Barbara Campbell', 11, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Ready', 'Alexander Williams', 8, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Ever debate agent', 'Chelsea Sexton', 23, 18);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Meeting play east', 'Mrs. Debra King', 25, 0);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Suggest somebody', 'Michael Frederick', 28, 19);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Several accept', 'Sara Guzman', 12, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Reality treatment', 'Kevin Parks', 10, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Here debate', 'Tiffany Hodges', 11, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Among speech', 'Brad Hardy', 16, 4);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Return suddenly', 'Brittany Stein', 25, 23);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Receive factor especially', 'Lisa Nguyen', 12, 12);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Wrong issue', 'Gary Jackson', 14, 12);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Common government father', 'Kimberly Kaufman', 19, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Lawyer ball', 'Aaron Norman', 9, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Eight', 'Heather Schneider', 19, 12);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Bed close school', 'Paul Lewis', 7, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Than speak', 'Shawn Baxter', 12, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Writer might', 'Gina Porter', 12, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Meeting cold', 'Thomas Friedman', 12, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Evening suggest', 'Anthony Erickson', 7, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Maintain', 'Karen Graham', 15, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Lose left treat', 'Sherri Harris', 22, 16);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Through population again', 'Annette Austin', 9, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Rock develop', 'John Gutierrez', 7, 6);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Analysis', 'Andrea Bauer', 23, 7);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Rise partner week', 'Kevin Lewis', 28, 17);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('What and wait', 'Colleen Rivas', 27, 16);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Style benefit rock', 'Walter Lee', 13, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Choose change red beyond', 'Barbara Rodriguez', 22, 14);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('There far', 'Robert Pratt', 13, 11);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Pretty lead full', 'Michael Smith', 26, 20);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Wait thought already mother', 'Kim May', 11, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Success population', 'Monica Li', 11, 8);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Into country present', 'Jesse Sherman', 7, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Game recognize', 'Nicole Rodriguez', 23, 18);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Financial base', 'Valerie French', 29, 12);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Board consumer', 'Annette Jimenez', 26, 21);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Successful laugh sometimes', 'Joseph Blackwell', 9, 3);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('They', 'Chad Gomez', 24, 9);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Floor send', 'Beverly Thompson', 9, 2);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Though pick site', 'Amy Roberts', 6, 1);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Billion step still participant', 'Jeremy Hill', 9, 5);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Take food drive', 'Tonya Freeman', 23, 21);
INSERT INTO books (bk_title, author, total_copies, available_copies) VALUES ('Director as', 'David White', 24, 7);



INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (9, 136, '2025-06-15', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (38, 124, '2025-06-14', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (85, 142, '2025-07-27', '2025-07-31', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (108, 111, '2025-07-26', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (5, 119, '2025-07-27', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (174, 114, '2025-07-06', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (187, 25, '2025-07-21', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (75, 143, '2025-06-08', '2025-07-20', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (75, 4, '2025-06-08', '2025-07-09', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (19, 156, '2025-07-07', '2025-07-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (13, 197, '2025-07-27', '2025-08-01', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (109, 190, '2025-07-13', '2025-07-30', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (123, 88, '2025-07-04', '2025-07-18', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (44, 125, '2025-07-26', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (156, 30, '2025-08-02', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (74, 186, '2025-07-01', '2025-07-16', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (86, 59, '2025-06-15', '2025-06-30', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (169, 21, '2025-06-12', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (117, 58, '2025-07-21', '2025-07-28', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (96, 15, '2025-07-29', '2025-07-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (77, 141, '2025-07-15', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (160, 147, '2025-07-02', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (179, 87, '2025-07-08', '2025-07-12', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (16, 187, '2025-06-14', '2025-08-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (155, 76, '2025-06-30', '2025-07-26', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (56, 120, '2025-06-24', '2025-06-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (63, 91, '2025-07-06', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (1, 196, '2025-07-17', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (120, 41, '2025-06-22', '2025-07-05', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (73, 176, '2025-07-09', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (41, 162, '2025-07-19', '2025-08-02', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (72, 30, '2025-06-08', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (8, 88, '2025-07-26', '2025-07-27', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (9, 89, '2025-07-23', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (173, 195, '2025-06-27', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (172, 87, '2025-07-12', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (146, 97, '2025-07-24', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (62, 41, '2025-07-17', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (171, 163, '2025-07-03', '2025-07-17', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (28, 6, '2025-07-01', '2025-07-02', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (101, 60, '2025-07-25', '2025-07-31', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (33, 47, '2025-07-25', '2025-08-01', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (65, 74, '2025-07-29', '2025-07-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (56, 21, '2025-06-24', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (178, 176, '2025-07-30', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (42, 159, '2025-06-28', '2025-08-02', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (64, 186, '2025-07-22', '2025-08-01', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (178, 144, '2025-06-15', '2025-07-05', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (191, 188, '2025-06-06', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (121, 112, '2025-07-29', '2025-07-30', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (51, 85, '2025-07-29', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (49, 137, '2025-06-07', '2025-06-28', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (66, 19, '2025-06-25', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (92, 15, '2025-07-28', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (3, 24, '2025-07-31', '2025-08-01', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (113, 8, '2025-07-26', '2025-07-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (191, 41, '2025-07-05', '2025-07-20', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (72, 192, '2025-07-10', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (156, 39, '2025-07-08', '2025-07-13', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (120, 191, '2025-07-20', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (158, 38, '2025-07-08', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (142, 81, '2025-07-07', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (157, 111, '2025-07-08', '2025-08-02', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (141, 10, '2025-06-26', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (145, 164, '2025-07-01', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (24, 36, '2025-07-26', '2025-08-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (46, 118, '2025-07-07', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (28, 12, '2025-06-19', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (194, 18, '2025-06-20', '2025-06-23', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (139, 14, '2025-07-06', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (72, 163, '2025-06-20', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (22, 15, '2025-06-08', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (70, 92, '2025-06-06', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (198, 159, '2025-06-08', '2025-06-10', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (99, 141, '2025-07-30', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (83, 51, '2025-07-15', '2025-07-21', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (91, 125, '2025-08-02', '2025-08-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (9, 133, '2025-07-13', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (39, 164, '2025-07-16', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (167, 63, '2025-06-25', '2025-06-25', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (182, 198, '2025-07-05', '2025-07-26', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (120, 28, '2025-06-25', '2025-06-26', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (149, 5, '2025-06-23', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (10, 96, '2025-06-12', '2025-06-23', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (48, 82, '2025-07-07', '2025-07-08', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (47, 103, '2025-06-13', '2025-06-17', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (106, 158, '2025-07-18', '2025-07-28', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (16, 51, '2025-06-15', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (140, 73, '2025-06-13', '2025-07-27', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (170, 21, '2025-07-05', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (137, 32, '2025-07-21', '2025-08-01', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (124, 41, '2025-07-30', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (53, 123, '2025-06-22', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (93, 135, '2025-07-20', '2025-07-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (128, 108, '2025-06-14', '2025-07-20', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (70, 196, '2025-07-06', '2025-08-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (63, 61, '2025-06-15', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (124, 108, '2025-07-31', '2025-08-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (135, 70, '2025-07-12', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (55, 133, '2025-07-27', '2025-07-27', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (92, 144, '2025-07-30', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (19, 101, '2025-06-21', '2025-07-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (175, 8, '2025-06-24', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (66, 7, '2025-07-23', '2025-08-01', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (6, 80, '2025-06-26', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (77, 154, '2025-06-15', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (174, 163, '2025-06-22', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (5, 46, '2025-07-22', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (118, 57, '2025-06-06', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (31, 90, '2025-07-08', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (124, 88, '2025-08-01', '2025-08-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (5, 178, '2025-08-01', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (123, 84, '2025-06-20', '2025-06-27', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (175, 55, '2025-07-01', '2025-07-20', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (194, 199, '2025-07-18', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (59, 177, '2025-07-05', '2025-07-09', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (183, 37, '2025-07-27', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (42, 73, '2025-07-23', '2025-08-01', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (98, 67, '2025-07-18', '2025-07-29', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (44, 132, '2025-07-05', '2025-07-23', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (5, 137, '2025-07-05', '2025-07-08', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (160, 52, '2025-07-25', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (94, 47, '2025-06-19', '2025-07-15', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (85, 29, '2025-06-27', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (161, 171, '2025-06-19', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (191, 197, '2025-06-18', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (119, 147, '2025-07-22', '2025-07-26', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (126, 55, '2025-07-21', '2025-08-04', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (198, 41, '2025-06-23', '2025-06-24', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (70, 80, '2025-07-06', '2025-07-14', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (196, 164, '2025-06-13', '2025-07-17', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (147, 31, '2025-06-16', '2025-07-21', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (88, 145, '2025-07-06', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (72, 195, '2025-07-23', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (100, 47, '2025-06-19', '2025-07-28', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (36, 44, '2025-07-12', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (38, 163, '2025-06-07', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (131, 173, '2025-07-11', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (57, 190, '2025-06-07', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (185, 87, '2025-06-19', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (125, 72, '2025-06-11', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (158, 34, '2025-06-19', '2025-07-25', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (23, 172, '2025-07-20', '2025-07-21', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (41, 128, '2025-07-25', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (81, 32, '2025-06-24', '2025-07-17', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (195, 12, '2025-06-09', '2025-06-18', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (186, 70, '2025-06-11', '2025-06-21', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (11, 121, '2025-08-03', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (46, 33, '2025-06-14', '2025-07-14', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (77, 132, '2025-07-29', '2025-08-02', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (5, 3, '2025-07-08', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (27, 185, '2025-07-07', '2025-07-20', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (51, 117, '2025-07-04', '2025-07-16', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (98, 62, '2025-07-14', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (188, 40, '2025-07-17', '2025-07-31', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (15, 46, '2025-06-09', '2025-06-16', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (179, 44, '2025-06-24', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (167, 21, '2025-06-18', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (63, 140, '2025-07-02', '2025-07-16', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (52, 57, '2025-07-04', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (77, 94, '2025-06-28', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (110, 200, '2025-06-25', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (76, 7, '2025-07-29', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (32, 37, '2025-06-19', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (181, 53, '2025-06-18', '2025-07-14', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (80, 199, '2025-06-09', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (131, 108, '2025-06-25', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (151, 152, '2025-08-01', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (41, 119, '2025-07-17', '2025-07-23', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (106, 88, '2025-06-15', '2025-07-22', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (79, 87, '2025-07-19', '2025-07-27', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (156, 119, '2025-07-05', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (158, 170, '2025-06-19', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (80, 193, '2025-07-29', '2025-08-02', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (130, 74, '2025-07-14', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (75, 165, '2025-07-09', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (185, 153, '2025-06-30', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (123, 183, '2025-08-03', '2025-08-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (153, 176, '2025-06-22', '2025-07-27', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (134, 111, '2025-07-14', '2025-07-17', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (63, 34, '2025-06-30', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (99, 93, '2025-07-15', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (88, 78, '2025-07-12', '2025-07-25', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (87, 181, '2025-06-22', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (4, 136, '2025-06-11', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (72, 121, '2025-06-21', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (131, 40, '2025-06-16', '2025-06-20', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (153, 143, '2025-06-18', '2025-07-20', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (26, 111, '2025-06-14', '2025-07-03', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (26, 56, '2025-07-16', NULL, 'Issued');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (5, 167, '2025-06-19', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (182, 18, '2025-07-16', '2025-08-04', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (109, 53, '2025-07-21', '2025-07-21', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (18, 89, '2025-06-17', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (115, 157, '2025-08-01', '2025-08-02', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (114, 193, '2025-07-06', NULL, 'Not Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (199, 101, '2025-06-28', '2025-07-15', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (48, 183, '2025-07-19', '2025-08-04', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (49, 145, '2025-07-05', '2025-07-16', 'Returned');
INSERT INTO borrow_records (book_id, cust_id, borrow_date, returned_date, bk_status) VALUES (3, 178, '2025-06-30', '2025-07-29', 'Returned');

-- Updated INSERT statements for Customers (phone <= 20, email <= 20)

INSERT INTO customers (cname, cemail, phone_no) VALUES ('William Horton MD', 'brownedward@hotmail.', '0643790562867');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Latasha Gordon', 'washingtonpaul@varga', '1843899831966');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mr. Connor Mann', 'traceybecker@phillip', '8555775784742');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Craig Williams', 'lflores@yahoo.com', '3661609834920');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Haley Beltran', 'acase@hernandez.com', '1389744786483');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Christopher Butler', 'qleonard@fox-thomas.', '2798597996700');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mr. John Randall', 'davidfisher@hotmail.', '2058925112122');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jennifer Clarke', 'egonzalez@johnson.ne', '8782274425751');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Tara Shaw', 'umorrison@bryant-fue', '0951005153780');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Keith Anderson', 'sarah83@merritt.com', '4350513310693');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Robert Mack', 'mercerluke@hotmail.c', '6551197730871');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Derek Lewis', 'hdoyle@harris.org', '3776753495046');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Brian Rodriguez', 'mthompson@martinez.i', '6256294419287');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mitchell Watkins', 'judycarter@acosta.or', '0345844418899');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kendra Smith', 'jonesrebekah@hotmail', '1310051397483');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ellen Dean', 'matthewmartinez@hotm', '4911781520550');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jeremiah Robinson', 'nancy28@gmail.com', '0440437294862');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Emily Collins', 'donnafoster@hotmail.', '6972318505421');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Allison Edwards', 'amber56@gmail.com', '9555001510086');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ashley Spencer', 'lisa65@hotmail.com', '8928069700556');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Alexander Perez', 'robin80@yahoo.com', '4717165597334');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Danielle Brooks', 'michaelhenderson@ste', '0215423990775');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Sheila Harvey', 'greenbrandi@price-po', '0287899946219');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michelle Jones', 'porterthomas@yahoo.c', '2077486940047');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Tabitha Gonzalez', 'anita73@lee.com', '6894571543079');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Christopher Hernandez', 'fbell@yahoo.com', '6237585936888');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mark Murphy', 'tonynewman@walker.bi', '2813856913088');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Stephen Shepherd', 'xflores@andersen.com', '8962582131727');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Steven Sutton', 'jeremiahscott@king.b', '9970679260553');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Maria Collier', 'simpsonmelanie@hotma', '0841118582583');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Alex Dawson', 'freese@hotmail.com', '6379578881419');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Danielle Flores', 'grossdavid@montgomer', '7994981419596');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Terri Gregory', 'josephgalvan@fry.com', '4595646253301');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Robin Baker', 'abigailsmith@gmail.c', '6504062002555');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Donna Wagner', 'petersonryan@carpent', '3036572997228');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kelsey Stevenson', 'lisa02@hotmail.com', '8639183662394');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mitchell Livingston', 'garrettburns@braun.c', '8918263875742');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Paul Atkins', 'williambenson@gmail.', '8614000097178');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Alec Tucker', 'phamelizabeth@yahoo.', '0359016905264');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('George Zamora', 'christophermartinez@', '6092193543824');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Nathan Wyatt', 'melissa65@yahoo.com', '7403319330981');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Patrick Malone', 'esmith@yahoo.com', '0699713169704');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('John Anthony', 'tgarcia@hotmail.com', '1066466611355');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Steven Walker', 'douglas60@gmail.com', '5832346799104');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kathryn Hill', 'autumnharrison@wilki', '4982901170240');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('James Garcia', 'james44@lambert.net', '5516071362817');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jacqueline Bradley', 'kimberlyjones@yahoo.', '6354440542269');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Adam Torres', 'ehenry@yahoo.com', '4020068325557');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Brandon Adams', 'millercynthia@yahoo.', '8335601420355');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Elizabeth Hobbs', 'sarah19@yahoo.com', '3806531066292');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mitchell Allen', 'quinnlaura@yahoo.com', '5379113711905');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jonathan Bailey', 'nthompson@cunningham', '9386546964000');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Logan Singh', 'kmorris@kelly.com', '0184059651024');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Raven Martinez', 'amy78@cunningham.com', '2028231926947');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Chelsea Petersen', 'daviskathy@hotmail.c', '1880254763292');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Regina Hammond', 'catherinemartinez@gm', '9433132261992');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Melissa Yu', 'nicholas20@yahoo.com', '8142777454474');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Rita Carpenter', 'vbell@gutierrez-buch', '5790253745981');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('John Long', 'harpersteven@hensley', '2856844189051');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ashley Shaw', 'samanthaevans@gmail.', '9947810887206');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Courtney Mclaughlin', 'valerie18@gmail.com', '4468222673705');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jennifer Powell', 'masonaustin@wilcox.c', '0851944806127');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Gregory Mitchell', 'laurenroberts@goodma', '5981765460041');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('James Andrade', 'clarkkenneth@hotmail', '5897901736889');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Stacy Stokes', 'boydkelsey@hotmail.c', '7461498989329');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Gary Mccarthy', 'amypineda@villegas.c', '7353408148940');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('David Meyer', 'wsmith@gmail.com', '3506790146579');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kelly Nelson', 'lmccoy@osborne.org', '3734763598917');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('David Anderson', 'margaret67@gmail.com', '4707494661162');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Johnathan Sosa', 'benjamin85@yahoo.com', '1500001230354');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Amy Mccoy', 'dannyrussell@huff.co', '1454877589900');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jeffrey Martin', 'johnny24@hotmail.com', '2110192786319');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Stephanie Daniels', 'johnheath@moore-evan', '8245220497939');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('David Jones', 'thomastorres@gmail.c', '3712929322897');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Devin Cook', 'hoffmandaniel@king.c', '1952187640392');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Aaron Boyd IV', 'karenhurst@hotmail.c', '7060081501142');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Nicholas Holt', 'bernardjeffrey@mcgui', '0068654906461');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Andrew Green', 'lmorales@clark.com', '9998125658025');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kristy Phillips', 'wellis@gmail.com', '9322702092825');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ian Bailey', 'andersonkelly@gmail.', '9971355513158');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Tonya Lopez', 'wrightdonna@gmail.co', '2533593668972');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Spencer Hamilton', 'xburton@hotmail.com', '6424703783998');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Joanne Blankenship', 'jeffrey53@russell.co', '8773697116789');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('John Garcia', 'kennedykristy@gmail.', '5805798548512');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Veronica Patel', 'mitchellhannah@hotma', '0056820713341');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Richard Mcclain', 'hansoncasey@hotmail.', '3763641780360');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Daniel Cole', 'josecarter@gmail.com', '4737616052210');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Eric Coleman', 'amandalarson@walker.', '0997460623154');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Melissa Terry', 'wedwards@hotmail.com', '6820409288150');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Laura Henson', 'mcneilamanda@yahoo.c', '4495765469319');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michael Yates', 'ryanmoore@fox-king.c', '0958205746954');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michael Travis', 'rebeccarice@hotmail.', '0096363951909');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Nicholas Lowe', 'meganyoung@yahoo.com', '8354502533511');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Hayley Evans', 'thomasrobert@craig.c', '4929319349439');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Crystal Salinas', 'taylordonald@gmail.c', '7504177188414');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Evan Boyd', 'michaelwelch@davis.c', '9757078399338');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Donald Jackson', 'garrettmendoza@marti', '5728331321359');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Sydney Adams', 'qstephens@smith-penn', '8783137557716');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michael Hall', 'agould@clark-murphy.', '6365499928174');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Lauren Scott', 'cdiaz@hotmail.com', '5448286475946');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Janet Martinez', 'hsmith@lyons.com', '0554943190419');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Amy Hamilton', 'kaylamanning@douglas', '4444800381225');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Angela Hall', 'tproctor@king.com', '1305280963298');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Frances Bright', 'kristadavis@gmail.co', '8643549613607');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jason King', 'kathleen68@woods.inf', '0484336004961');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Adam Allen', 'curtis26@hotmail.com', '3452331276304');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Danielle Lopez', 'cynthia91@gmail.com', '1189766727374');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Zachary Ferguson', 'juanbell@gmail.com', '1725068997368');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Cynthia Dominguez', 'ycollins@marshall-ra', '5815340990722');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Isaac Robertson', 'gwendolyn84@conner.c', '5996738666703');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kiara Burns', 'djohnson@moss-mendez', '0553679083993');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Stacy Thomas', 'nsteele@booth-ramire', '3999887090577');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Chelsea Williams', 'rodriguezerin@gmail.', '9467037222878');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Danielle Lang', 'caseygomez@yahoo.com', '4938640085143');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Nicole Miller', 'maldonadoautumn@doug', '0792538540271');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kyle Martinez', 'cohenmargaret@floyd.', '2298705887586');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michael Brown', 'phillip05@cantrell.i', '5815695523824');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jessica Peters', 'mia98@brown.com', '7508519567555');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Lisa Davila', 'brookejohnson@yahoo.', '4420593383432');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Thomas Barnett', 'wramos@williams.net', '5018218586696');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Melissa Boyd', 'wallacebrian@yahoo.c', '9644730335121');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Sandra Huff', 'willisbryan@hotmail.', '3720607178178');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Stephanie Moore', 'larrybrooks@jones.co', '9845236536461');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Abigail Gill', 'dana44@yahoo.com', '9799119955295');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('April Lewis', 'paula52@pierce.com', '3932402632927');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Brenda Wilson', 'jack62@gmail.com', '3843489609618');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Matthew Prince', 'perezjennifer@hotmai', '3577958957125');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jennifer Castillo', 'halelee@cowan.com', '9439050934802');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michael Sanchez', 'crystalbrooks@yahoo.', '2076961146481');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Becky Brown', 'kmiller@gmail.com', '1687762844387');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Lisa Payne', 'ppeters@yahoo.com', '1422879272842');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mr. Christopher Thompson PhD', 'veronica40@anderson.', '0421469488029');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Robin Hogan', 'jeffrey86@ruiz.com', '1611511069682');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Teresa Bauer', 'smithshannon@martine', '6056821839105');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Andre Raymond', 'qrojas@foster.org', '2363176268975');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Abigail Ellis', 'acostachad@gmail.com', '3501159741587');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Daniel Norman MD', 'dmiller@pratt.net', '5437654013890');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ms. Renee Russell', 'nataliebrown@clark.i', '8863909270717');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Vanessa Cisneros', 'dylan17@joyce-cox.co', '5355891315093');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ariel Frye', 'barryboyle@gmail.com', '5632078986338');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Tyler Scott', 'melissadavis@yahoo.c', '9091972156845');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Angela Torres', 'harrisonjohn@hotmail', '2393116991181');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Robin Hall', 'benjaminnguyen@escob', '1306212074311');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Maria Dyer', 'timothyarmstrong@hot', '2834780008087');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Alexa Sloan', 'sgardner@gmail.com', '2463011418668');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kenneth Gibson', 'hillemily@gmail.com', '5880413655604');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Justin Collins', 'lwalls@martinez.com', '0226270693695');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Debra Lee', 'micheleanderson@gmai', '8933875461327');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Veronica Potter', 'christian75@smith.or', '7707192389297');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jennifer Wright', 'rivasfrancisco@hotma', '7378064196147');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Carlos Wood', 'justin08@hotmail.com', '0436437330528');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Daniel Coffey', 'gregory15@carroll.bi', '6743296766195');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Sarah Thomas', 'kristinaanderson@lee', '9578508460532');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('David Townsend', 'wreyes@willis.org', '6739323658978');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ashley Bolton', 'david93@gmail.com', '4818761480744');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Jared Boyd', 'philipfuller@huynh-m', '7072414015752');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michael Blake', 'hallchristine@hotmai', '5851864438274');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kimberly Wells', 'rmiles@rogers.com', '3494258456427');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Catherine Medina', 'jonesedward@gmail.co', '1766464237670');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Melissa Martin', 'nicholas01@yahoo.com', '4213506624279');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Michael Oconnell', 'mary52@yahoo.com', '5846674258419');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kimberly Reyes', 'elizabethjenkins@mar', '2731440908438');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mario Anderson', 'tschultz@hotmail.com', '3825421573224');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Natalie Wall', 'phutchinson@hotmail.', '3608876074199');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Matthew Chapman', 'sullivanthomas@yahoo', '4457237324797');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kayla Wong', 'meganmartinez@yahoo.', '0103367628632');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Lisa Little', 'cory47@hotmail.com', '9962647240970');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Becky Robinson', 'ssalazar@gmail.com', '6919168497369');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Robin Russo MD', 'dfernandez@moreno.co', '4549736991465');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Suzanne Watts', 'reynoldsronald@russo', '8131208309566');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Ariel Murphy', 'martinezchristopher@', '1523118682783');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Gloria White', 'fmejia@yahoo.com', '7670914545333');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('William Valenzuela', 'lhinton@cunningham.c', '0138363676396');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Theresa Lopez', 'allison32@hotmail.co', '5406594466598');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Gabrielle Perez', 'ronaldjames@yahoo.co', '1347793912381');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Christopher Collier', 'natalie70@gmail.com', '4091764047605');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Joshua Evans', 'zferguson@hotmail.co', '9680138625548');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Laurie Kent', 'natalie63@hayes.com', '4488788290742');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Mr. William Davis DDS', 'reidwilliam@gonzalez', '2511573890927');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Christopher Miranda', 'jeffreyruiz@hotmail.', '1998557160059');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Brandon Anderson', 'daniel85@hotmail.com', '9616146403204');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Daniel Mccarthy', 'armstrongkelly@mille', '4088985444337');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('John Black', 'larry16@villanueva.c', '9993245863860');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Christopher Davis', 'heather43@yahoo.com', '8546555117555');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kristin Edwards', 'kpatel@moss.com', '5700834259255');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('James Torres', 'wandaadams@oneal-smi', '4469285387556');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Christopher Goodwin', 'jaredcollins@joseph.', '5325167446773');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Rachel Jones', 'christopheroneal@gma', '5553095079289');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Diane Pittman DDS', 'nancytorres@yahoo.co', '8339832204113');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Megan Kennedy', 'nicolemyers@yahoo.co', '5488994521503');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('David Johnson', 'murphyjodi@hotmail.c', '0562887371258');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Curtis Parker', 'matthew89@erickson.c', '4803315737123');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Dr. Amanda Clements', 'paul26@stewart.info', '6229471144614');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Edward Long', 'shorn@gmail.com', '8931768045813');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Rachel Wiley', 'gonzalezmonique@yaho', '0815300547441');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Warren Harvey', 'murrayjaime@yahoo.co', '4851724548855');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kristin Clay', 'toni07@hotmail.com', '6085497776307');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Matthew Mcpherson', 'matthewbaxter@gmail.', '3850236916789');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Kelsey Lynch', 'patricia40@walters.c', '8152615371834');
INSERT INTO customers (cname, cemail, phone_no) VALUES ('Catherine Fuller', 'joshualee@hotmail.co', '1005228917703');